
INSERT INTO TB_CARGO VALUES (1,'PROGRAMADOR');
INSERT INTO TB_CARGO VALUES (2,'ANALISTA');
INSERT INTO TB_CARGO VALUES (3,'GERENTE');
INSERT INTO TB_CARGO VALUES (4,'ADMINISTRADOR');
INSERT INTO TB_CARGO VALUES (5,'COPEIRA');


INSERT INTO TB_SETOR VALUES (1,'ADMINISTRAÇÃO');
INSERT INTO TB_SETOR VALUES (2,'PRODUÇÃO');
INSERT INTO TB_SETOR VALUES (3,'FINANCEIRO');
INSERT INTO TB_SETOR VALUES (4,'RH');
INSERT INTO TB_SETOR VALUES (5,'DESENVOLVIMENTO');

INSERT INTO TB_CIDADE VALUES (1,'SALVADOR');
INSERT INTO TB_CIDADE VALUES (2,'ITABUNA');
INSERT INTO TB_CIDADE VALUES (3,'LAURO DE FREITAS');

COMMIT;