-- Criação das tabelas
CREATE TABLE ESPECTADOR (
  ID_ESPECTADOR  INT NOT NULL,
  NOME           VARCHAR(50) NOT NULL,
  BAIRRO         VARCHAR(30) NOT NULL,
  SEXO           CHAR(1) NOT NULL,
  PRIMARY KEY (ID_ESPECTADOR)
);

CREATE TABLE FILME (
  ID_FILME       INT NOT NULL,
  TITULO         VARCHAR(30) NOT NULL,
  DURACAO        INT NOT NULL,
  PRIMARY KEY (ID_FILME)
);

CREATE TABLE SALA (
  ID_SALA        INT NOT NULL,
  NUMERO         INT NOT NULL,
  CAPACIDADE     INT NOT NULL,
  SITUACAO       CHAR(1) NOT NULL,
  PRIMARY KEY (ID_SALA)
);

CREATE TABLE SESSAO (
  ID_SESSAO      INT NOT NULL,
  ID_SALA        INT NOT NULL,
  ID_FILME       INT NOT NULL,
  DATA_HORA      TIMESTAMP NOT NULL,
  PRIMARY KEY (ID_SESSAO),
  FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA),
  FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME)
);

CREATE TABLE INGRESSO (
  ID_INGRESSO    INT NOT NULL,
  ID_ESPECTADOR  INT NOT NULL,
  ID_SESSAO      INT NOT NULL,
  VALOR_PAGO     REAL NOT NULL,
  PRIMARY KEY (ID_INGRESSO),
  FOREIGN KEY (ID_ESPECTADOR) REFERENCES ESPECTADOR(ID_ESPECTADOR),
  FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID_SESSAO)
);

-- Criação das sequências
CREATE SEQUENCE SQ_ESPECTADOR;
CREATE SEQUENCE SQ_FILME;
CREATE SEQUENCE SQ_SALA;
CREATE SEQUENCE SQ_SESSAO;
CREATE SEQUENCE SQ_INGRESSO;
